### ISSUE TITLE
Allow custom record serialization for interactive queries

### ISSUE THREAD

**Issue by Fryuni** [streamthoughts/azkarra-streams#61]
We use custom avro serialization in our state-stores. Because of that, we got this error while trying to do an interactive query for debugging:
```
io.streamthoughts.azkarra.http.error.SerializationException: Error happens while serializing object 'io.streamthoughts.azkarra.api.query.result.QueryResult@65026665'
	at io.streamthoughts.azkarra.http.json.JsonSerdes.serialize(JsonSerdes.java:167)
	at io.streamthoughts.azkarra.http.ExchangeHelper.sendJsonResponseWithCode(ExchangeHelper.java:115)
	at io.streamthoughts.azkarra.http.ExchangeHelper.sendJsonResponse(ExchangeHelper.java:101)
	at io.streamthoughts.azkarra.http.handler.ApplicationQueryStoreHandler.handleRequest(ApplicationQueryStoreHandler.java:65)
	at io.streamthoughts.azkarra.http.handler.WithApplication.handleRequest(WithApplication.java:38)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:376)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class com.croct.platform.domain.tracking.ClientId and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: io.streamthoughts.azkarra.api.query.result.QueryResult["result"]->io.streamthoughts.azkarra.api.query.result.GlobalResultSet["success"]->java.util.ArrayList[0]->io.streamthoughts.azkarra.api.query.result.SuccessResultSet["records"]->java.util.ArrayList[0]->io.streamthoughts.azkarra.api.model.KV["value"]->com.croct.platform.domain.tracking.SessionSubject["clientId"])
	at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:77)
	at com.fasterxml.jackson.databind.SerializerProvider.reportBadDefinition(SerializerProvider.java:1191)
	at com.fasterxml.jackson.databind.DatabindContext.reportBadDefinition(DatabindContext.java:404)
	at com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.failForEmpty(UnknownSerializer.java:71)
	at com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.serialize(UnknownSerializer.java:33)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:727)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:722)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:166)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:2795)
	at com.fasterxml.jackson.core.base.GeneratorBase.writeObject(GeneratorBase.java:388)
	at io.streamthoughts.azkarra.http.json.serializers.WindowedSerializer.serialize(WindowedSerializer.java:43)
	at io.streamthoughts.azkarra.http.json.serializers.WindowedSerializer.serialize(WindowedSerializer.java:31)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:727)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:722)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:166)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:119)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:79)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:18)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:727)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:722)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:166)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:119)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:79)
	at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:18)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:727)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:722)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:166)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:727)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:722)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:166)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
	at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:4094)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:3404)
	at io.streamthoughts.azkarra.http.json.JsonSerdes.serialize(JsonSerdes.java:165)
	... 9 more
```

I think a possible solution would be exposing a static `registerModule` or `registerSerializer` on the `JsonSerdes` class so we can add our custom serializers along with the default ones like [here](https://github.com/streamthoughts/azkarra-streams/blob/174715c2611e6fc29dd9c87d061ff36cf1154041/azkarra-server/src/main/java/io/streamthoughts/azkarra/http/json/JsonSerdes.java#L63)

**Comment by fhussonnois** [comment]
Hi @Fryuni,  you said that you are using avro serialization for records but is your classes : 
* `com.croct.platform.domain.tracking.ClientId`
* `com.croct.platform.domain.tracking.SessionSubject` 

are generated from avro schemas - do they extend GenericRecord or IndexRecord ?

But yes, we should support custom serializers. I will work on your issue to have a fix for the coming release.

**Comment by fhussonnois** [comment]
BTW, the JSON serialization has been refactored for the next release (0.7). A dedicated Maven module has been created to hold all serializers (this is helpful to integrate Azkarra with others frameworks). In addition, the `JsonSerdes` class has been removed so I can't just add a static method.

I propose to follow same mechanism than Spring. Thus, you will be able to register a Jackson Module as a component. Azkarra will then automatically add all modules registred into `AzkarrraContext` to the `ObjectMapper`.

Does that solution suits you need ? Thanks.

**Comment by marcospassos** [comment]
> are generated from avro schemas - do they extend GenericRecord or IndexRecord ?

We use a custom Avro serializer for those objects.

> I propose to follow same mechanism than Spring. Thus, you will be able to register a Jackson Module as a component. Azkarra will then automatically add all modules registred into AzkarrraContext to the ObjectMapper.
> 
> Does that solution suits you need ? Thanks.
Jackson is exactly the library we use for serialization. If you guys provide a way to register custom modules, it may address the issue. But in our case, the data is serialized in Avro. How will Azkarra deserialize from Avro into JSON? Could you clarify how it will work?

**Comment by fhussonnois** [comment]
Currently, Azkarra registers a [`GenericRecordSerializer`](https://github.com/streamthoughts/azkarra-streams/blob/v0.6.1/azkarra-server/src/main/java/io/streamthoughts/azkarra/http/json/serializers/GenericRecordSerializer.java) to serialize objects implementing [`GenericRecord` ](https://avro.apache.org/docs/1.7.6/api/java/org/apache/avro/generic/GenericRecord.html) into JSON

This serializer should handle case where Avro classes are generated from schema (i.e `.avsc`) because those classes extend the [`SpecificRecordBase` ](https://avro.apache.org/docs/1.7.6/api/java/org/apache/avro/specific/SpecificRecordBase.html)class which implements the GenericRecord interface.

But this seems to not be your case. Normally, you should be able to annotate your Java classes with `@JsonSerialize` to specifiy a custom serializer.

Now, what I'm proposing is to be able to register custom serializers as follows : 

```java
        context.registerComponent(Module.class, () -> {
            SimpleModule module = new SimpleModule();
            module.addSerializer(MyCustomType.class, new MyCustomSerializer());
            return module;
        } );
```

**Comment by marcospassos** [comment]
thanks for clarifying, @fhussonnois!

We already bundle our custom serializers into modules, so it should address our case without any changes.

Any estimate for the release including this new feature?

Thank you!

**Comment by fhussonnois** [comment]
Azkarra v0.7 should be released next week.
